In [ ]:
import pandas as pd

In [69]:
df = pd.read_csv('Car Dataset Processed.csv')

In [70]:
df.head(2)

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99

In [ ]:
df.columns

Index(['Unnamed: 0', 'car_name', 'registration_year', 'insurance_validity',
       'fuel_type', 'seats', 'kms_driven', 'ownsership', 'transmission',
       'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)',
       'torque(Nm)', 'price(in lakhs)'],
      dtype='object')

In [72]:
df['insurance_validity'].value_counts()

insurance_validity
Comprehensive            1081
Third Party insurance     289
Zero Dep                   64
Third Party                63
Not Available               2
Name: count, dtype: int64

In [ ]:
k1 = {'Comprehensive':0, 'Third Party insurance':1, 'Zero Dep':2, 'Not Available':3, 'Third Party':1}
df['insurance_validity'] = df['insurance_validity'].map(k1)

In [74]:
df['insurance_validity'].value_counts()

insurance_validity
0    1081
1     352
2      64
3       2
Name: count, dtype: int64

In [75]:
df['fuel_type'].value_counts()

fuel_type
Petrol    997
Diesel    480
CNG        22
Name: count, dtype: int64

In [76]:
k2 = {'Petrol':1,'Diesel':2,'CNG':3}
df['fuel_type'] = df['fuel_type'].map(k2)

In [77]:
df['fuel_type'].value_counts()

fuel_type
1    997
2    480
3     22
Name: count, dtype: int64

In [78]:
df['transmission'].value_counts()

transmission
Manual       832
Automatic    667
Name: count, dtype: int64

In [79]:
k4 = {'Manual':7,'Automatic':8}
df['transmission'] = df['transmission'].map(k4)
df['transmission'].value_counts()

transmission
7    832
8    667
Name: count, dtype: int64

In [80]:
df['ownsership'].value_counts()

ownsership
First Owner     1236
Second Owner     240
Third Owner       21
Fifth Owner        2
Name: count, dtype: int64

In [81]:
k3 = {'First Owner':1,'Second Owner':2,'Third Owner':3,'Fifth Owner':5}
df['ownsership'] = df['ownsership'].map(k3)

In [82]:
df['ownsership'].value_counts()

ownsership
1    1236
2     240
3      21
5       2
Name: count, dtype: int64

In [83]:
df['registration_year']

0       Jul-17
1       Jan-21
2       Sep-18
3       Dec-19
4       Aug-19
         ...
1494    May-22
1495    Aug-20
1496    Jun-17
1497    May-18
1498    May-18
Name: registration_year, Length: 1499, dtype: object

In [95]:
#df['registration_year'].value_counts()

In [85]:
X = df[['insurance_validity','fuel_type','kms_driven','ownsership','transmission']] 
y = df['price(in lakhs)']

In [86]:
X.head()

   insurance_validity  fuel_type  kms_driven  ownsership  transmission
0                   0          1       56000           1             8
1                   0          1       30615           1             8
2                   0          2       24000           1             8
3                   0          1       18378           1             7
4                   0          1       44900           1             8

In [87]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [88]:
models = {'LinReg':LinearRegression(),
         'KNN-3':KNeighborsRegressor(n_neighbors = 3),
         'SVN-Poly':SVR(kernel='poly')}
for name,model in models.items():
    model.fit(X,y)
    sc= model.score(X,y)
    print(name,sc)

LinReg 0.01881841973825704
KNN-3 0.5927605118086187
SVN-Poly -0.0021593397176471463

In [89]:
final_model = models['KNN-3']

In [103]:
k1 = {'Comprehensive':0,'Third Party insurance':1,'Zero Dep':2,'Not Available':3,'Third Party':1}
k2 = {'Petrol':1,'Diesel':2,'CNG':3}
k3 = {'First Owner':1,'Second Owner':2,'Third Owner':3,'Fifth Owner':5}
k4 = {'Manual':7,'Automatic':8}

In [106]:
insurance_validity = input('Insurance_validity:')
fuel_type = input('Fuel_type:')
kms_driven = input('Kms Driven:')
ownsership = input('Ownership:')
transmission = input('Transmission Type:')
insurance_validity = k1[insurance_validity]
fuel_type = k2[fuel_type]
ownsership = k3[ownsership]
transmission = k4[transmission]
kms_driven = int(kms_driven)
test = [[insurance_validity,fuel_type,kms_driven,ownsership,transmission]]
yp = int(final_model.predict(test)[0])
print('Predicted Price of the Car is {} $$.'.format(yp))

Insurance_validity: Zero Dep
Fuel_type: Petrol
Kms Driven: 35000
Ownership: First Owner
Transmission Type: Manual

Predicted Price of the Car is 5 $$.

C:\Users\Shivam\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [107]:
import pickle
pickle.dump(final_model,open('final_model.pkl','wb'))